ExceptionMessages:
  Enabled: true

ExceptionMessages/Casing:
  Description: 'Checks the capitalization of raised exception messages.'
  Enabled: true
  EnforcedStyle: lowercase
  SupportedStyles:
    - lowercase
    - uppercase
  VersionAdded: '0.1'
  VersionChanged: '0.2'

ExceptionMessages/Punctuation:
  Description: 'Checks the trailing punctuation of raised exception messages.'
  Enabled: true
  EnforcedStyle: no_period
  SupportedStyles:
    - no_period
    - period
  VersionAdded: '0.1'
  VersionChanged: '0.2'
